// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Utils$Repaco = require("./Utils.bs.js");

function aParser(str) {
  var xs = Utils$Repaco.string_to_list(str);
  console.log(xs);
  var res = xs ? (
      xs[0] === "A" ? /* tuple */[
          true,
          Utils$Repaco.list_to_string(xs[1])
        ] : /* tuple */[
          false,
          str
        ]
    ) : /* tuple */[
      false,
      ""
    ];
  console.log("RES:", res);
  return res;
}

exports.aParser = aParser;
/* No side effect */
