// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Parser$Repaco = require("../src/Parser.bs.js");

Jest.describe("Parse ABC", (function (param) {
        var input = "ABC";
        var actual = Parser$Repaco.aParser(input);
        Jest.test("succeed with ABC", (function (param) {
                return Jest.Expect[/* toEqual */12](/* tuple */[
                            true,
                            "BC"
                          ], Jest.Expect[/* expect */0](actual));
              }));
        var actual$1 = Parser$Repaco.aParser("XBC");
        Jest.test("fail with no matchable string", (function (param) {
                return Jest.Expect[/* toEqual */12](/* tuple */[
                            false,
                            "XBC"
                          ], Jest.Expect[/* expect */0](actual$1));
              }));
        var actual$2 = Parser$Repaco.aParser("");
        return Jest.test("fail with empty string", (function (param) {
                      return Jest.Expect[/* toEqual */12](/* tuple */[
                                  false,
                                  ""
                                ], Jest.Expect[/* expect */0](actual$2));
                    }));
      }));

/*  Not a pure module */
